enc:
  size: [8500, 8500]
  center: [269780.2502465503, 7039561.05833144]
  depths: [0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500]
  resources: [/, data/, data/db/]

display:
  colorbar: false
  dark_mode: true
  fullscreen: false
  resolution: 720
  anchor: center
  dpi: 96
