enc:
  size: [6500, 6500]
  center: [271794.3121781586, 7042820.867264936]
  depths: [0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500]
  resources: [/, data/, data/db/]

display:
  colorbar: false
  dark_mode: true
  fullscreen: false
  resolution: 720
  anchor: center
  dpi: 96
