enc:
  size: [2500, 2500]
  center: [269982.2863602937, 7044463.540428318]
  depths: [0, 1, 2, 5, 10, 20, 50, 100, 200, 350, 500]
  resources: [/, data/, data/db/]

display:
  colorbar: false
  dark_mode: true
  fullscreen: false
  resolution: 720
  anchor: center
  dpi: 96
